# The MIT License (MIT)
#
# Copyright (c) 2015 Arthur Fabre <arthur@arthurfabre.com>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

#############
# Generic makefile settings for C, CPP, and ASM.
#
# Supports automatic dependecy generation, cross compiling, and other bits of magic.
# Expects to be using the GNU C Compiler, or a compatible compiler.
#
# A seperate directory is created in the bin directory for every architecture.
#
# Dependecies are generated at compile time - we only need updated dependecy information for the next build.
#
# Directory makefiles should include settings.mk first. 
# They can then override / append the variables defined in the Settings section
#
# They should then include rules.mk
# They can then override / create new build rules
#
#############

#############
# Settings - all of these variables are recursively expanded so that users can override them
#############

# Path to source directory
SRCDIR=src/

# Source file extensions
SRC_EXTENSIONS=c s cpp

# Common dependencies of source files
SOURCE_DEPS+=

# Path(s) to libraries
LIBDIRS=lib/ ../lib/

# Path(s) to additional includes
INCLUDEDIRS+=

# Object directory. A subdirectory will be created per architecture
BINDIR=bin/

# Auto-generated code directory
GEN_SRCDIR=$(BINDIR)src/

# List of autogenerated source files
GEN_SOURCES+=

# OutputName. @ represents the name of the directory containing this makefile
OUTPUT_NAME=@.elf

# Libraries
LIBRARIES+=

# CrossCompile options
CROSS_COMPILE+=

# C Options. Will be passed to C and C++ compiler
C_OPTS+= -c -Wall -O3 -Werror -pedantic

# Options to generate dependency information. Passed to C and C++ compiler
# MD: Generate a file with makefile style dependencies along with the object files
# MP; Generate bogus empty rules for every dependency so that deleting them doesn't break make
DEPENDS_OPTS=-MD -MP

# ASM compiler to use
AS=$(CROSS_COMPILE)gcc -x assembler-with-cpp
AS_OPTS+=

# C Compiler to use
CC=$(CROSS_COMPILE)gcc
CC_OPTS+= -std=gnu11

# C++ Compiler to use
CPP=$(CROSS_COMPILE)g++
CPP_OPTS+= -std=gnu++11

# Objcopy to use
OBJCOPY=$(CROSS_COMPILE)objcopy
OBJCOPY_OPTS+=

# Linker to use
LD=$(CROSS_COMPILE)g++
LD_OPTS+=
